Embedded Systems Library: Wait Public Functions
Wait Public Functions
Wait
Functions
void wait_init ()
Initialises the wait API for 1 ms resolution.
uint32_t wait_elapsed (uint32_t time)
Counts the time that has passed since the time received.
void wait_ms (int milis)
Waits a number of milliseconds.
void SysTick_Handler (void)
__MS increment.
void wait_hz (int frequency)
Waints a number of hertz.
Detailed Description
Function Documentation
SysTick_Handler()
void SysTick_Handler (void)
__MS increment.
Definition at line 12 of file Wait.c.
References __MS.
wait_elapsed()
uint32_t wait_elapsed (uint32_t time)
Counts the time that has passed since the time received.
Parameters
time initial time.
Returns
millis: the time that has passed.
Definition at line 16 of file Wait.c.
References __MS.
wait_hz()
void wait_hz (int frequency)
Waints a number of hertz.
Parameters
hertz the whole number of hertz to wait.
Definition at line 21 of file Wait.c.
References wait_ms().
wait_init()
void wait_init ()
Initialises the wait API for 1 ms resolution.
Returns
0 if initialisation successed; -1 if fails.
Note
This function must be called prior to any other WAIT functions.
Definition at line 3 of file Wait.c.
Referenced by init_ui().
wait_ms()
void wait_ms (int milis)
Waits a number of milliseconds.
Parameters
millis the whole number of milliseconds to wait.
Definition at line 7 of file Wait.c.
References __MS.
Referenced by wait_hz().