Embedded Systems Library: SPI Public Functions
SPI Public Functions
SPI
Functions
void init_spi (void)
Initialize SPI functions.
int SPI_ConfigTransfer (int frequency, int bitData, int mode)
set SPI transfers configurations
int SPI_Transfer (unsigned short *txBuffer, unsigned short *rxBuffer, int length)
perform a transfer of data.
Detailed Description
Function Documentation
init_spi()
void init_spi (void)
Initialize SPI functions.
Note
must be called first
Definition at line 11 of file SPI.c.
References BIT_ENABLE_BIT_POSITION, BITS_MODE, LSBF_BIT_POSITION, MASTER_MODE, MASTER_MODE_BIT_POSITION, MSB_MODE_L, PCLK_CCLK_FUNCTION_L, PCLK_SPI_BIT_POSITION, PINSEL_MISO_BIT_POS, PINSEL_MOSI_BIT_POS, PINSEL_SCK_BIT_POS, and SPI_FUNCTION.
Referenced by init_peripherals().
SPI_ConfigTransfer()
int SPI_ConfigTransfer (int frequency, int bitData, int mode)
set SPI transfers configurations
Definition at line 21 of file SPI.c.
References BITS_BIT_POSITION, BITS_MASK, CPHA_CPOL_BIT_MASK, CPHA_CPOL_BIT_POSITION, CPHA_CPOL_HH, CPHA_CPOL_LL, CUSTOM_CONFIG_TRANSFER, DEFAULT_DATABIT, DEFAULT_FREQUENCY, DEFAULT_MODE, FIFTEEN_BITS, mode, ret, and SIXTEEN_BITS.
Referenced by get_chip_ID(), and measure().
SPI_Transfer()
int SPI_Transfer (unsigned short * txBuffer, unsigned short * rxBuffer, int length)
perform a transfer of data.
Returns
success or error
Definition at line 47 of file SPI.c.
References SPIF.