Embedded Systems Library: D:/Isel/19-20/Inverno/SE1/SE1920/src/lcd.c File Reference
lcd.c File Reference
#include "lcd.h"
Functions
void LCDText_Write_4bits (int rs, int data)
void LCDText_Send_4bits (int rs, int data)
void LCDText_Init (void)
void write_pin (int val, int pin)
void LCDText_WriteChar (char ch)
void LCDText_WriteString (char *str)
void LCDText_Locate (int row, int column)
void LCDText_Clear (void)
void LCDText_Printf (char *fmt,...)
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Definition at line 64 of file lcd.c.
References CLEAR_DISPLAY_CMD, COMMAND, and LCDText_Write_4bits().
LCDText_Init()
void LCDText_Init (void)
Definition at line 7 of file lcd.c.
References B_POSITION, BLINK_CURSOR_OFF, C_POSITION, CLEAR_DISPLAY_CMD, COMMAND, CURSOR_OFF, D_POSITION, DISPLAY_CONTROL_CMD, DISPLAY_OFF, DISPLAY_ON, DL_POSITION, ENTRY_MODE_SET_CMD, F_POSITION, FOUR_BIT, FUNCTION_SET_CMD, I_D_POSITION, INCREMENT, INIT_VAL, LCD_DB4, LCD_DB5, LCD_DB6, LCD_DB7, LCD_ENABLE, LCD_RS, LCDText_Send_4bits(), LCDText_Write_4bits(), N_POSITION, PINCFG_DB4, PINCFG_DB5, PINCFG_DB6, PINCFG_DB7, PINCFG_ENABLE, PINCFG_RS, RETURN_HOME_CMD, S_POSITION, SHIFT_ENABLE, TEN_DOT_FONT, TWO_LINES, wait_ChronoUs(), and wait_ms().
Referenced by init_ui().
LCDText_Locate()
void LCDText_Locate (int row, int column)
Definition at line 60 of file lcd.c.
References COMMAND, LCDText_Write_4bits(), MAX_COL_VALUE, ROW_POSITION, and SET_DDRAM_ADDR_CMD.
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Definition at line 68 of file lcd.c.
LCDText_Send_4bits()
void LCDText_Send_4bits (int rs, int data)
Definition at line 40 of file lcd.c.
References DATA, LCD_DB4, LCD_DB5, LCD_DB6, LCD_DB7, LCD_ENABLE, LCD_RS, wait_ChronoUs(), and write_pin().
Referenced by LCDText_Init(), and LCDText_Write_4bits().
LCDText_Write_4bits()
void LCDText_Write_4bits (int rs, int data)
Definition at line 29 of file lcd.c.
References LCDText_Send_4bits(), and wait_ChronoUs().
Referenced by LCDText_Clear(), LCDText_Init(), LCDText_Locate(), and LCDText_WriteChar().
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Definition at line 53 of file lcd.c.
References DATA, and LCDText_Write_4bits().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Definition at line 56 of file lcd.c.
write_pin()
void write_pin (int val, int pin)
Definition at line 35 of file lcd.c.
Referenced by LCDText_Send_4bits().