Embedded Systems Library: LCD Public Functions
LCD Public Functions
lcd
This package provides the public functions of the LCD Display.
Functions
void LCDText_Init (void)
LCD instruction initialization function to be able to send and control the LCD using 4 bits.
void LCDText_WriteChar (char ch)
Writes the given character on the LCD in the current cursor position.
void LCDText_WriteString (char *str)
Writes the given string on the LCD in the current cursor position.
void LCDText_Locate (int row, int column)
Put the cursor in the given position of the lcd.
void LCDText_Clear (void)
Clear the LCD Display.
void LCDText_Printf (char *fmt,...)
Writes the given string on the LCD in the current cursor position using a certain format.
Detailed Description
This package provides the public functions of the LCD Display.
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Clear the LCD Display.
Note
The cursor goes back to the initial position, first line (0) and first column (0).
Definition at line 77 of file lcd.c.
References CLEAR_DISPLAY_CMD, COMMAND, LCDText_Write_4bits(), and wait_ms().
LCDText_Init()
void LCDText_Init (void)
LCD instruction initialization function to be able to send and control the LCD using 4 bits.
Note
Call this function only at the beginning of the program and only once
Definition at line 10 of file lcd.c.
References B_POSITION, BLINK_CURSOR_OFF, C_POSITION, CLEAR_DISPLAY_CMD, col, COMMAND, CURSOR_OFF, D_POSITION, DISPLAY_CONTROL_CMD, DISPLAY_OFF, DISPLAY_ON, DL_POSITION, ENTRY_MODE_SET_CMD, F_POSITION, FOUR_BIT, FUNCTION_SET_CMD, I_D_POSITION, INCREMENT, INIT_VAL, LCD_DB4, LCD_DB5, LCD_DB6, LCD_DB7, LCD_ENABLE, LCD_RS, LCDText_Send_4bits(), LCDText_Write_4bits(), N_POSITION, PINCFG_DB4, PINCFG_DB5, PINCFG_DB6, PINCFG_DB7, PINCFG_ENABLE, PINCFG_RS, RETURN_HOME_CMD, row, S_POSITION, SHIFT_ENABLE, TEN_DOT_FONT, TWO_LINES, wait_ChronoUs(), and wait_ms().
Referenced by init_ui().
LCDText_Locate()
void LCDText_Locate (int row, int column)
Put the cursor in the given position of the lcd.
Parameters
row put the cursor at the first (0) or the second line(1).
column put the cursor at the given column (0-15).
Definition at line 71 of file lcd.c.
References col, COMMAND, LCDText_Write_4bits(), MAX_COL_VALUE, row, ROW_POSITION, and SET_DDRAM_ADDR_CMD.
Referenced by LCDText_Printf(), and LCDText_WriteString().
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Writes the given string on the LCD in the current cursor position using a certain format.
Parameters
fmt String to write.
Note
identical to the C printf library.
Definition at line 82 of file lcd.c.
References col, LCDText_Locate(), LCDText_WriteChar(), and row.
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes the given character on the LCD in the current cursor position.
Parameters
ch character to write.
Definition at line 58 of file lcd.c.
References DATA, and LCDText_Write_4bits().
Referenced by LCDText_Printf(), and LCDText_WriteString().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes the given string on the LCD in the current cursor position.
Parameters
str string to write.
Note
this function can change between lines if the string is to large
Definition at line 61 of file lcd.c.
References col, LCDText_Locate(), LCDText_WriteChar(), and row.